export const restaurantsData = [
	{
		id: 0,
		name: "McDonald's",
		img: "./images/restaurants/McDonald's.jpg",
		category: ['Fast Food'],
		price: '$',
		stars: 4.1,
		rating: 8900,
		distance: 1.4,
		deliveryTime: 14,
		isAd: true,
		isPopular: true,
		isNearYou: true,
		isLiked: true,
	},
	{
		id: 1,
		name: 'Chipotle',
		img: './images/restaurants/Chipotle.webp',
		category: ['Mexican'],
		price: '$$',
		stars: 4.2,
		rating: 3200,
		distance: 2.1,
		deliveryTime: 28,
		isAd: true,
		isPopular: false,
		isNearYou: true,
		isLiked: false,
	},
	{
		id: 2,
		name: 'Sushi Nami',
		img: './images/restaurants/Sushi.jpg',
		category: ['Asian'],
		price: '$$',
		stars: 4.0,
		rating: 2700,
		distance: 6.2,
		deliveryTime: 53,
		isAd: false,
		isPopular: false,
		isNearYou: false,
		isLiked: false,
	},
	{
		id: 3,
		name: 'Panera',
		img: './images/restaurants/Panera.jpg',
		category: ['Sandwiches', 'Salad'],
		price: '$',
		stars: 4.6,
		rating: 2000,
		distance: 5.3,
		deliveryTime: 47,
		isAd: false,
		isPopular: false,
		isNearYou: false,
		isLiked: false,
	},
	{
		id: 4,
		name: 'Starbucks',
		img: './images/restaurants/Starbucks.jpg',
		category: ['Drinks'],
		price: '$',
		stars: 4.8,
		rating: 5800,
		distance: 5.7,
		deliveryTime: 55,
		isAd: true,
		isPopular: true,
		isNearYou: false,
		isLiked: false,
	},
	{
		id: 5,
		name: 'Wawa',
		img: './images/restaurants/Wawa.jpg',
		category: ['Sandwiches', 'Salad', 'Drinks'],
		price: '$',
		stars: 4.5,
		rating: 7000,
		distance: 0.4,
		deliveryTime: 19,
		isAd: true,
		isPopular: false,
		isNearYou: true,
		isLiked: false,
	},
	{
		id: 6,
		name: 'Taco Bell',
		img: './images/restaurants/TacoBell.jpg',
		category: ['Fast Food', 'Mexican'],
		price: '$',
		stars: 4.2,
		rating: 2500,
		distance: 1.9,
		deliveryTime: 22,
		isAd: false,
		isPopular: true,
		isNearYou: true,
		isLiked: false,
	},
	{
		id: 7,
		name: "Pho Kitch'n",
		img: "./images/restaurants/PhoKitch'n.jpg",
		category: ['Asian'],
		price: '$$',
		stars: 4.1,
		rating: 1000,
		distance: 5.2,
		deliveryTime: 52,
		isAd: false,
		isPopular: false,
		isNearYou: false,
		isLiked: false,
	},
];
